# Generated by Django 4.2.4 on 2023-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_alter_category_about_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eduQuaImg',
            field=models.FileField(blank=True, null=True, upload_to='User Edu Qua'),
        ),
    ]
