# Generated by Django 4.2.4 on 2023-08-18 15:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_eduquaimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userID',
            field=models.CharField(default=app.models.generate_unique_id, max_length=6, unique=True),
        ),
    ]
