# Generated by Django 4.2.4 on 2023-08-24 16:56

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_email_alter_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('productType', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.TextField()),
                ('bank', models.TextField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='storeitem',
            name='vendor',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
            preserve_default=False,
        ),
    ]
